-- 인물 이미지 120장 objectKey/출처/라이선스/버전 반영 (이슈 #207)
-- id 11,12,32,34,50,62,71,80,88,91,93,108,117: 출처 미확인(나무위키 프로필 등, license=UNKNOWN).
-- 자진 수용 리스크로 이미 운영 반영 완료 — 자세한 배경은 #207 참고.
-- 선행: 2026-09-16_celebrity_image_license_version.sql (image_license_version 컬럼 추가) 먼저 적용
-- 배포 순서: 1) upload_s3.sh 실행 완료 후  2) 이 SQL 실행
-- 출처 검증 완료된 인물만 포함

UPDATE celebrity SET image_url = 'celebrity/1/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3A5.3.10RichardBransonByDavidShankbone.jpg', image_author = 'User:David Shankbone' WHERE id = 1; -- 리처드 브랜슨
UPDATE celebrity SET image_url = 'celebrity/2/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3AKyle-cassidy-neil-gaiman-April-2013.jpg', image_author = 'Kyle Cassidy' WHERE id = 2; -- 닐 게이먼
UPDATE celebrity SET image_url = 'celebrity/3/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Ben_Shapiro_(49290212823)_(cropped).jpg', image_author = 'Gage Skidmore' WHERE id = 3; -- 벤 샤피로
UPDATE celebrity SET image_url = 'celebrity/4/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Neil_deGrasse_Tyson_in_June_2017.jpg', image_author = 'Norwegian University of Science and Technology' WHERE id = 4; -- 닐 디그래스 타이슨
UPDATE celebrity SET image_url = 'celebrity/5/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=73El1ZBsf1s', image_author = 'Marie Claire Korea' WHERE id = 5; -- 페이커
UPDATE celebrity SET image_url = 'celebrity/6/profile_v1.webp', image_license = 'PUBLIC_DOMAIN', image_license_version = NULL, image_source_url = 'https://commons.wikimedia.org/wiki/File:P20260418DT-0015_President_Donald_J._Trump_holds_a_press_conference_after_signing_an_Executive_Order_accelerating_medical_treatments_for_serious_mental_illness.jpg', image_author = 'The White House' WHERE id = 6; -- 조 로건
UPDATE celebrity SET image_url = 'celebrity/7/profile_v1.webp', image_license = 'CC_BY', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3AArianna_Huffington_%283018740818%29.jpg', image_author = 'JD Lasica from Pleasanton, CA, US' WHERE id = 7; -- 애리애나 허핑턴
UPDATE celebrity SET image_url = 'celebrity/8/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=WLBthg6vKAE', image_author = 'SBS Radio 에라오' WHERE id = 8; -- 찰스엔터
UPDATE celebrity SET image_url = 'celebrity/9/profile_v1.webp', image_license = 'CC_BY', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:100405_EasterEggRoll_683_(4513125422).jpg', image_author = 'Daniel Ogren' WHERE id = 9; -- J.K. 롤링
UPDATE celebrity SET image_url = 'celebrity/10/profile_v1.webp', image_license = 'CC_BY', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Bill_Gates_at_the_European_Commission_-_P067383-987995.jpg', image_author = 'Bogdan Hoyaux / European Union' WHERE id = 10; -- 빌 게이츠
UPDATE celebrity SET image_url = 'celebrity/11/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 11; -- 노은솔
UPDATE celebrity SET image_url = 'celebrity/12/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 12; -- 황석희
UPDATE celebrity SET image_url = 'celebrity/13/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3AReese_Witherspoon_at_TIFF_2014.jpg', image_author = 'dtstuff9' WHERE id = 13; -- 리즈 위더스푼
UPDATE celebrity SET image_url = 'celebrity/14/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3A%EA%B3%A0%EB%AF%BC%EC%8B%9C%EC%99%80_%ED%95%A8%EA%BB%98%ED%95%9C_%EB%B7%B0%ED%8B%B0%ED%99%94%EB%B3%B4_02.png', image_author = 'Marie Claire Korea' WHERE id = 14; -- 고민시
UPDATE celebrity SET image_url = 'celebrity/15/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=UfE5Ly26LaE', image_author = 'VISIT BUSAN' WHERE id = 15; -- 최태성
UPDATE celebrity SET image_url = 'celebrity/16/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=vem6dF21m5k', image_author = '부산음악창작소' WHERE id = 16; -- 하림
UPDATE celebrity SET image_url = 'celebrity/17/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=7lu1LP6pLp4', image_author = '카오스 사이언스' WHERE id = 17; -- 최재천
UPDATE celebrity SET image_url = 'celebrity/18/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3ALee_Ju-yeon_%28%EC%9D%B4%EC%A3%BC%EC%97%B0%29_200817.jpg', image_author = 'Marie Claire Korea' WHERE id = 18; -- 주연
UPDATE celebrity SET image_url = 'celebrity/20/profile_v1.webp', image_license = 'PUBLIC_DOMAIN', image_license_version = NULL, image_source_url = 'https://commons.wikimedia.org/wiki/File:Elon_Musk_Colorado_2022_(cropped2).jpg', image_author = 'U.S. Air Force / Trevor Cokley' WHERE id = 20; -- 일론머스크
UPDATE celebrity SET image_url = 'celebrity/21/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=q0Sg4eFkuzE', image_author = 'BEARS TV' WHERE id = 21; -- 문현빈
UPDATE celebrity SET image_url = 'celebrity/19/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=dt2KVr4kCLA', image_author = '방언니 - 방송국에 사는 언니들' WHERE id = 19; -- 김이나
UPDATE celebrity SET image_url = 'celebrity/22/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3ALee_Juck_20161109_02.png', image_author = 'KBS 뷰' WHERE id = 22; -- 이적
UPDATE celebrity SET image_url = 'celebrity/23/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=IVe4TwyMhDg', image_author = 'SBS Radio 에라오' WHERE id = 23; -- 김영철
UPDATE celebrity SET image_url = 'celebrity/24/profile_v1.webp', image_license = 'PUBLIC_DOMAIN', image_license_version = NULL, image_source_url = 'https://commons.wikimedia.org/wiki/File%3APresident_Barack_Obama.jpg', image_author = 'Official White House Photo by Pete Souza' WHERE id = 24; -- 오바마
UPDATE celebrity SET image_url = 'celebrity/25/profile_v1.webp', image_license = 'PUBLIC_DOMAIN', image_license_version = NULL, image_source_url = 'https://commons.wikimedia.org/wiki/File:Oprah_Winfrey_2016.jpg', image_author = 'US Embassy South Africa' WHERE id = 25; -- 오프라 윈프리
UPDATE celebrity SET image_url = 'celebrity/26/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=vsm6vLQ1hkg', image_author = '미미미누' WHERE id = 26; -- 이지영
UPDATE celebrity SET image_url = 'celebrity/27/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Park_Chan-wook_at_the_2026_Cannes_Film_Festival_by_YantsImages_02.jpg', image_author = 'YantsImages' WHERE id = 27; -- 박찬욱
UPDATE celebrity SET image_url = 'celebrity/28/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=KKvr2U1P--Q', image_author = '롯데엔터테인먼트' WHERE id = 28; -- 이동진
UPDATE celebrity SET image_url = 'celebrity/29/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=4Dbj300LmCQ', image_author = '조준호(ZOZNO)' WHERE id = 29; -- 조준호
UPDATE celebrity SET image_url = 'celebrity/30/profile_v1.webp', image_license = 'CC_BY', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Hanroro_(한로로)_World_Vision_Korea_2025.jpg', image_author = '월드비전 World Vision Korea' WHERE id = 30; -- 한로로
UPDATE celebrity SET image_url = 'celebrity/31/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=v9x7ZnQcEfc', image_author = 'MAXPORTS' WHERE id = 31; -- 백성동
UPDATE celebrity SET image_url = 'celebrity/32/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 32; -- 밍기뉴
UPDATE celebrity SET image_url = 'celebrity/33/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Stephen_King_at_the_2024_Toronto_International_Film_Festival_2.jpg', image_author = 'Kevin Payravi' WHERE id = 33; -- 스티븐 킹
UPDATE celebrity SET image_url = 'celebrity/34/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 34; -- 빨간 모자쌤
UPDATE celebrity SET image_url = 'celebrity/35/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=oY7VGkVWjsM', image_author = '퍼니콘 (Funnycon)' WHERE id = 35; -- 요조
UPDATE celebrity SET image_url = 'celebrity/36/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=l_Fqmq0qHlg', image_author = 'K-POPIT 케이팝잇' WHERE id = 36; -- 원필
UPDATE celebrity SET image_url = 'celebrity/37/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Dahyun_at_press_conference_for_You_Are_the_Apple_of_My_Eye_02.png', image_author = 'https://www.youtube.com/@_TV10/videos' WHERE id = 37; -- 다현
UPDATE celebrity SET image_url = 'celebrity/38/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Han_Kang,_2024_Nobel_Prize_Laureate_in_Literature.jpg', image_author = 'John Sears' WHERE id = 38; -- 한강
UPDATE celebrity SET image_url = 'celebrity/39/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:BTS_RM_and_V_military_discharge,_10_June_2025_01.png', image_author = 'K-POPIT 케이팝잇' WHERE id = 39; -- RM
UPDATE celebrity SET image_url = 'celebrity/40/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3A2018_%EC%9D%B8%EB%94%94%EC%8A%A4%EB%95%85%EC%8A%A4_%ED%8C%8C%EC%9D%B4%EB%84%90_%EC%BD%98%EC%84%9C%ED%8A%B8_%EC%9E%94%EB%82%98%EB%B9%84_%EC%B5%9C%EC%A0%95%ED%9B%88_3.jpg', image_author = 'Explicit' WHERE id = 40; -- 최정훈
UPDATE celebrity SET image_url = 'celebrity/41/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:(%EC%8B%B9%ED%8A%9C%EB%B8%8C)_%EC%84%9C%EC%A2%85%EC%98%88_%EB%B0%A9%EC%86%A1MC_%EC%9E%84%EC%84%B1%EC%96%B8_%ED%95%99%EC%83%9D_-_%EB%B0%95%EC%9E%AC%EB%AF%BC_%EA%B5%90%EC%88%98_%EC%9D%B8%ED%84%B0%EB%B7%B0_(%EB%93%9C%EB%9D%BC%EB%A7%88_%EC%99%95%EC%9D%98%EC%96%BC%EA%B5%B4%2C_%EC%A1%B0%EC%84%A0%EC%B4%9D%EC%9E%A1%EC%9D%B4%2C_%EC%B6%9C%EB%B0%9C%EB%93%9C%EB%A6%BC%ED%8C%80_%EC%B6%9C%EC%97%B0!).jpg', image_author = '서울종합예술실용학교 공식 영상채널 싹튜브' WHERE id = 41; -- 박재민
UPDATE celebrity SET image_url = 'celebrity/42/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:이재성_(축구_선수).jpg', image_author = 'GOAL TV' WHERE id = 42; -- 이재성
UPDATE celebrity SET image_url = 'celebrity/43/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:%EC%8B%A0%ED%95%B4%EC%B2%A0.jpg', image_author = 'MBC PD수첩' WHERE id = 43; -- 신해철
UPDATE celebrity SET image_url = 'celebrity/44/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=CRzo0MQ38fM', image_author = 'KAIST' WHERE id = 44; -- 정재승
UPDATE celebrity SET image_url = 'celebrity/45/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=usVT9qq3hmo', image_author = 'LionsTV' WHERE id = 45; -- 박상원
UPDATE celebrity SET image_url = 'celebrity/46/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Anderson_Cooper_(44675408934).jpg', image_author = 'Gage Skidmore' WHERE id = 46; -- 앤더슨 쿠퍼
UPDATE celebrity SET image_url = 'celebrity/47/profile_v1.webp', image_license = 'CC_BY', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3ABong_Joon_Ho_-_Okja.jpg', image_author = 'Kevin Paul' WHERE id = 47; -- 봉준호
UPDATE celebrity SET image_url = 'celebrity/48/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Emma_Watson_ONU_2017.jpg', image_author = 'ONU Brasil' WHERE id = 48; -- 엠마 왓슨
UPDATE celebrity SET image_url = 'celebrity/49/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Winter_aespa_(%EC%97%90%EC%8A%A4%ED%8C%8C)_231124_Love_Your_W.png', image_author = 'K-POPIT 케이팝잇' WHERE id = 49; -- 윈터
UPDATE celebrity SET image_url = 'celebrity/50/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 50; -- 김봉진
UPDATE celebrity SET image_url = 'celebrity/51/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=lVG2WzgoqGM', image_author = '카오스 사이언스' WHERE id = 51; -- 김상욱
UPDATE celebrity SET image_url = 'celebrity/52/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=1qzxlED3Ge4', image_author = 'BEARS TV' WHERE id = 52; -- 오명진
UPDATE celebrity SET image_url = 'celebrity/53/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3A%EC%A7%80%EC%83%81%EB%A0%AC_%EC%B6%9C%EC%97%B0_%ED%95%9C%EC%9A%B0_%EA%B3%B1%EC%B0%BD_%EC%8A%A4%ED%8E%98%EC%85%9C_%EB%8F%84%EB%B4%89%EA%B5%AC_%EB%8F%84%EB%B4%89%EB%8F%99_%EB%A7%9B%EC%A7%91_%EC%82%BC%EC%98%A4%EC%A7%91_%28%EC%8B%9D%EC%8B%A0%EB%A1%9C%EB%93%9C_Gourmet_Road%29_EP_170-2.jpg', image_author = 'Official Youtube account of 식신로드 (Gourmet Road), its twitter' WHERE id = 53; -- 지상렬
UPDATE celebrity SET image_url = 'celebrity/54/profile_v1.webp', image_license = 'CC_BY', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:140904_%ED%83%80%EB%B8%94%EB%A1%9C_02_%28cropped%29.jpg', image_author = 'pabian' WHERE id = 54; -- 타블로
UPDATE celebrity SET image_url = 'celebrity/55/profile_v1.webp', image_license = 'CC_BY', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3ASeo_Su-bin_-_Yoon_Ga-eun_at_the_2025_Red_Sea_Film_Festival_20251206_%282%29.jpg', image_author = 'Zafer' WHERE id = 55; -- 윤가은
UPDATE celebrity SET image_url = 'celebrity/56/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Moon_Ga-young_in_September_2024_02.png', image_author = 'K-POPIT 케이팝잇' WHERE id = 56; -- 문가영
UPDATE celebrity SET image_url = 'celebrity/57/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:20210915—Park_Jeong-min_박정민_and_Im_Yoon-ah_임윤아,_costumed_photo_shoot,_Marie_Claire_Korea_screenshot_(00m13s).jpg', image_author = 'Marie Claire Korea' WHERE id = 57; -- 박정민
UPDATE celebrity SET image_url = 'celebrity/58/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:250313_Kim_Hye_Soo_%28%EA%B9%80%ED%98%9C%EC%88%98%29.png', image_author = 'K-POPIT 케이팝잇' WHERE id = 58; -- 김혜수
UPDATE celebrity SET image_url = 'celebrity/59/profile_v1.webp', image_license = 'PUBLIC_DOMAIN', image_license_version = NULL, image_source_url = 'https://commons.wikimedia.org/wiki/File%3ASarah_Silverman_DNC_July_2016.jpg', image_author = 'Ali Shaker/VOA' WHERE id = 59; -- 사라 실버먼
UPDATE celebrity SET image_url = 'celebrity/60/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Kim_Tae-ri_PRADA_BEAUTY_Photo_call_August_2024.png', image_author = 'K-POPIT 케이팝잇' WHERE id = 60; -- 김태리
UPDATE celebrity SET image_url = 'celebrity/61/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=C7VRFtGMSdg', image_author = 'YS Lee' WHERE id = 61; -- 이도윤
UPDATE celebrity SET image_url = 'celebrity/62/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 62; -- 문지혁
UPDATE celebrity SET image_url = 'celebrity/63/profile_v1.webp', image_license = 'PUBLIC_DOMAIN', image_license_version = NULL, image_source_url = 'https://commons.wikimedia.org/wiki/File:Hillary_Clinton_official_Secretary_of_State_portrait_crop.jpg', image_author = 'United States Department of State' WHERE id = 63; -- 힐러리 로댐 클린턴
UPDATE celebrity SET image_url = 'celebrity/64/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:220618_%EC%98%A4%EB%A7%88%EC%9D%B4%EA%B1%B8_%EC%9C%A0%EC%95%84.jpg', image_author = '티비텐' WHERE id = 64; -- 유아
UPDATE celebrity SET image_url = 'celebrity/65/profile_v1.webp', image_license = 'CC_BY', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:171018_%EC%95%88%ED%98%95%EC%84%AD.jpg', image_author = 'clip' WHERE id = 65; -- 안형섭
UPDATE celebrity SET image_url = 'celebrity/66/profile_v1.webp', image_license = 'CC_BY', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:%EC%86%8C%EB%85%80%EC%8B%9C%EB%8C%80_%EC%84%9C%ED%98%84_%27Better_Me%27_%ED%86%A0%ED%81%AC%EC%87%BC_in_%EC%8B%9C%ED%8B%B0_%ED%8F%AC%EB%A0%88%EC%8A%A4%ED%8B%B0%EB%B2%8C_%285%29.jpg', image_author = 'sj' WHERE id = 66; -- 서현
UPDATE celebrity SET image_url = 'celebrity/67/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=dI31F_AMeUk', image_author = 'SBS Radio 에라오' WHERE id = 67; -- 이석훈
UPDATE celebrity SET image_url = 'celebrity/68/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=CpOoD2yx89c', image_author = 'BEARS TV' WHERE id = 68; -- 채은성
UPDATE celebrity SET image_url = 'celebrity/69/profile_v1.webp', image_license = 'CC_BY', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Chen_at_busking_event_in_Seoul_on_August_31%2C_2019.png', image_author = '92CHEN0921_' WHERE id = 69; -- 첸
UPDATE celebrity SET image_url = 'celebrity/70/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:221013_Lily_%28NMIXX%29_Airport_Departure.jpg', image_author = 'K-POPIT 케이팝잇' WHERE id = 70; -- 릴리
UPDATE celebrity SET image_url = 'celebrity/71/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 71; -- 쩜
UPDATE celebrity SET image_url = 'celebrity/72/profile_v1.webp', image_license = 'CC_BY', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Anthony_Bourdain_and_Charlie_Rose_2014.jpg', image_author = 'Peabody Awards' WHERE id = 72; -- 앤서니 보데인
UPDATE celebrity SET image_url = 'celebrity/73/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Tony_Robbins_gesturing.jpg', image_author = 'Randy Stewart' WHERE id = 73; -- 앤서니 라빈스
UPDATE celebrity SET image_url = 'celebrity/74/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:20260722_%EC%82%AC%EB%9E%91%EC%9D%B4_%EC%98%A8%EB%8B%A4_%EC%A0%9C%EC%9E%91%EB%B0%9C%ED%91%9C%ED%9A%8C_%ED%95%98%EC%84%9D%EC%A7%84Ha_Seok-jin_2.png', image_author = 'K-POPIT 케이팝잇' WHERE id = 74; -- 하석진
UPDATE celebrity SET image_url = 'celebrity/75/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Jang_Won-young_IVE_Marie_Claire_Korea.jpg', image_author = 'Marie Claire Korea' WHERE id = 75; -- 장원영
UPDATE celebrity SET image_url = 'celebrity/76/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:%EA%B9%80%EC%A0%95%ED%98%84_%EC%95%84%EB%82%98%EC%9A%B4%EC%84%9C.jpg', image_author = '14F 일사에프' WHERE id = 76; -- 김정현
UPDATE celebrity SET image_url = 'celebrity/77/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Yves_LOONA_220625.jpg', image_author = 'SBS Radio 에라오' WHERE id = 77; -- 이브
UPDATE celebrity SET image_url = 'celebrity/78/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=usVT9qq3hmo', image_author = 'LionsTV' WHERE id = 78; -- 김범수
UPDATE celebrity SET image_url = 'celebrity/79/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3AAnna_Kendrick_Cannes_2016_2.jpg', image_author = 'Georges Biard' WHERE id = 79; -- 켄드릭 안나
UPDATE celebrity SET image_url = 'celebrity/80/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 80; -- 김서현
UPDATE celebrity SET image_url = 'celebrity/81/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Jennifer_Lawrence_SDCC_2015_X-Men.jpg', image_author = 'Gage Skidmore' WHERE id = 81; -- 제니퍼 로렌스
UPDATE celebrity SET image_url = 'celebrity/82/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3A251018_FC_%EC%84%9C%EC%9A%B8_vs_%ED%8F%AC%ED%95%AD_%28%EA%B9%80%EC%A2%85%EC%9A%B0%29.jpg', image_author = 'Explicit' WHERE id = 82; -- 김종우
UPDATE celebrity SET image_url = 'celebrity/83/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=EnxeEp5Oe-U', image_author = 'SBS Radio 에라오' WHERE id = 83; -- 뉴진스님
UPDATE celebrity SET image_url = 'celebrity/84/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Will_Smith_by_Gage_Skidmore_2.jpg', image_author = 'Gage Skidmore' WHERE id = 84; -- 윌 스미스
UPDATE celebrity SET image_url = 'celebrity/85/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Han_So-hee_%ED%95%9C%EC%86%8C%ED%9D%AC_20240516_01_%28cropped%29.jpg', image_author = '티비텐' WHERE id = 85; -- 한소희
UPDATE celebrity SET image_url = 'celebrity/86/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Pyo_Chang-won_Pandora_161207.png', image_author = 'ItsNEWKorea' WHERE id = 86; -- 표창원
UPDATE celebrity SET image_url = 'celebrity/87/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=XDOlwHINpdo', image_author = 'SBS Radio 에라오' WHERE id = 87; -- 김사월
UPDATE celebrity SET image_url = 'celebrity/88/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 88; -- 유즈
UPDATE celebrity SET image_url = 'celebrity/89/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:IVE%27s_Gaeul_In_January_2023.jpg', image_author = 'TenAsia' WHERE id = 89; -- 가을
UPDATE celebrity SET image_url = 'celebrity/90/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3AYang_Sangmoon_2025.jpg', image_author = 'Seohae1999' WHERE id = 90; -- 양상문
UPDATE celebrity SET image_url = 'celebrity/91/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 91; -- 황현희
UPDATE celebrity SET image_url = 'celebrity/92/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Arnold_Schwarzenegger_by_Gage_Skidmore_4.jpg', image_author = 'Gage Skidmore' WHERE id = 92; -- 아놀드 슈워제네거
UPDATE celebrity SET image_url = 'celebrity/93/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 93; -- 황희승
UPDATE celebrity SET image_url = 'celebrity/94/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=8Ij2sB2WNoc', image_author = 'MediaChangbi 미디어창비' WHERE id = 94; -- 유시민
UPDATE celebrity SET image_url = 'celebrity/95/profile_v1.webp', image_license = 'CC_BY', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Melinda_Gates,_Co-founder,_Bill_and_Melinda_Gates_Foundation_(15222588424).jpg', image_author = 'Chatham House, London' WHERE id = 95; -- 멀린다 게이츠
UPDATE celebrity SET image_url = 'celebrity/96/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:190501_%EC%9D%B4%EC%84%A4_(1).jpg', image_author = '뉴스인스타' WHERE id = 96; -- 이설
UPDATE celebrity SET image_url = 'celebrity/97/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Russell_Brand_(5622481884).jpg', image_author = 'Eva Rinaldi' WHERE id = 97; -- 러셀 브랜드
UPDATE celebrity SET image_url = 'celebrity/98/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:250718_IU_%28%EC%95%84%EC%9D%B4%EC%9C%A0%29.png', image_author = '티비텐 TV10' WHERE id = 98; -- 아이유
UPDATE celebrity SET image_url = 'celebrity/99/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3A251018_FC_%EC%84%9C%EC%9A%B8_vs_%ED%8F%AC%ED%95%AD_%28%EC%8B%A0%EA%B4%91%ED%9B%88%29_1.jpg', image_author = 'Explicit' WHERE id = 99; -- 신광훈
UPDATE celebrity SET image_url = 'celebrity/100/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:2017_Young_K_Taiwan.jpg', image_author = 'Shuohyun' WHERE id = 100; -- 영케이
UPDATE celebrity SET image_url = 'celebrity/101/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:John_Legend_2019_by_Glenn_Francis.jpg', image_author = 'Toglenn (Glenn Francis)' WHERE id = 101; -- 존 레전드
UPDATE celebrity SET image_url = 'celebrity/102/profile_v1.webp', image_license = 'CC_BY', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Ashton_Kutcher_by_David_Shankbone_2010_NYC.jpg', image_author = 'David Shankbone' WHERE id = 102; -- 애쉬튼 쿠처
UPDATE celebrity SET image_url = 'celebrity/103/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:20230829_Im_Soojung_%EC%9E%84%EC%88%98%EC%A0%95_02.jpg', image_author = 'K-POPIT 케이팝잇' WHERE id = 103; -- 임수정
UPDATE celebrity SET image_url = 'celebrity/104/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Jack_Dorsey_2014.jpg', image_author = 'cellanr' WHERE id = 104; -- 잭 도시
UPDATE celebrity SET image_url = 'celebrity/105/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Elizabeth_Warren_(47992252913).jpg', image_author = 'Gage Skidmore' WHERE id = 105; -- 엘리자베스 워런
UPDATE celebrity SET image_url = 'celebrity/106/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=pOYosX4iOM0', image_author = 'LionsTV' WHERE id = 106; -- 김재성
UPDATE celebrity SET image_url = 'celebrity/107/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Kim_So-hyun_at_the_Gladiator_II_VIP_premiere%2C_November_2024.png', image_author = 'Lotte Entertainment' WHERE id = 107; -- 김소현
UPDATE celebrity SET image_url = 'celebrity/108/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 108; -- 리틀타네
UPDATE celebrity SET image_url = 'celebrity/109/profile_v1.webp', image_license = 'CC_BY', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3AOh_Hyun-Kyung.jpg', image_author = 'KIYOUNG KIM' WHERE id = 109; -- 오현경
UPDATE celebrity SET image_url = 'celebrity/110/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Shin_Se-kyung_%EC%8B%A0%EC%84%B8%EA%B2%BD_in_January_2024_03.jpg', image_author = 'K-POPIT 케이팝잇' WHERE id = 110; -- 신세경
UPDATE celebrity SET image_url = 'celebrity/111/profile_v1.webp', image_license = 'CC_BY', image_license_version = '3.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3A181018%E2%80%94Huh_Yun-jin_%ED%97%88%EC%9C%A4%EC%A7%84_Hera_Seoul_Fashion_week.jpg', image_author = 'NewsInstar' WHERE id = 111; -- 허윤진
UPDATE celebrity SET image_url = 'celebrity/112/profile_v1.webp', image_license = 'CC_BY', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3AMindy_Kaling_May_2019.jpg', image_author = 'Montclair Film' WHERE id = 112; -- 민디 케일링
UPDATE celebrity SET image_url = 'celebrity/113/profile_v1.webp', image_license = 'CC_BY', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File%3ASon_Jong-won_and_Max_Changmin_for_LG.jpg', image_author = 'LG전자' WHERE id = 113; -- 손종원
UPDATE celebrity SET image_url = 'celebrity/114/profile_v1.webp', image_license = 'CC_BY', image_license_version = NULL, image_source_url = 'https://www.youtube.com/watch?v=CsjkJeGf_mE', image_author = 'SBS Radio 에라오' WHERE id = 114; -- 오은영
UPDATE celebrity SET image_url = 'celebrity/115/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '4.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Professor_Brian_Cox_OBE_FRS.jpg', image_author = 'Duncan.Hull' WHERE id = 115; -- 브라이언 콕스
UPDATE celebrity SET image_url = 'celebrity/116/profile_v1.webp', image_license = 'CC_BY_SA', image_license_version = '2.5', image_source_url = 'https://commons.wikimedia.org/wiki/File:Tom_Hanks_2016.jpg', image_author = 'Dick Thomas Johnson' WHERE id = 116; -- 톰 행크스
UPDATE celebrity SET image_url = 'celebrity/117/profile_v1.webp', image_license = 'UNKNOWN', image_license_version = NULL, image_source_url = '', image_author = '' WHERE id = 117; -- 신형철
UPDATE celebrity SET image_url = 'celebrity/118/profile_v1.webp', image_license = 'CC_BY', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Jon_Stewart_MFF_2016.jpg', image_author = 'Montclair Film Festival' WHERE id = 118; -- 존 스튜어트
UPDATE celebrity SET image_url = 'celebrity/119/profile_v1.webp', image_license = 'CC0', image_license_version = NULL, image_source_url = 'https://commons.wikimedia.org/wiki/File%3AMike_Bloomberg_Headshot.jpg', image_author = 'Bloomberg Philanthropies' WHERE id = 119; -- 마이클 블룸버그
UPDATE celebrity SET image_url = 'celebrity/120/profile_v1.webp', image_license = 'CC_BY', image_license_version = '2.0', image_source_url = 'https://commons.wikimedia.org/wiki/File:Reuni%C3%A3o_com_o_ator_norte-americano_Keanu_Reeves_%28cropped%29.jpg', image_author = 'Governo do Estado de São Paulo' WHERE id = 120; -- 키아누 리브스
